### ISSUE TITLE
RDP tunnel through ssh

### ISSUE THREAD

**Issue by sarpedon333** [qwj/python-proxy#109]
Hi! based on this [article](https://www.fireeye.com/blog/threat-research/2019/01/bypassing-network-restrictions-through-rdp-tunneling.html) i want to do something like this using python proxy (because plink is a disaster and i am looking for a neater way to accomplish this):

```
plink -v -N -T -C -noagent -ssh -R 31337:127.0.0.1:3389 -pw "[SSH_PASSWORD]" -2 -4 -D [PROXY_SERVER]:[PROXY_PORT] root@[SSH_SERVER]
```
basically I want to do a remote mapping of my RDP port to a random port (31337) on the SSH server but to bypass firewall I also have to use a proxy to achieve this matter (for the proxy I am already using a solution and it is not my case here), is it possible to replace plink with python proxy in this scenario? 
Cheers!

**Comment by qwj** [comment]
It is possible with pproxy, but with multiple commands.

On the client:
```
pproxy -l tunnel+in://127.0.0.1:1234 -r tunnel://127.0.0.1:3389
pproxy -l tunnel://:1234 -r ssh://remote_ssh#user::ssh_key_file__tunnel://localhost:1234
```

On the SSH server:
```
pproxy -l tunnel://0.0.0.0:31337 -r tunnel+in://127.0.0.1:1234
```

**Comment by qwj** [comment]
The latest pproxy v2.6.3 can use following command:
On the client:
```
pproxy -l ssh://remote_ssh#user::key__tunnel://127.0.0.1:12345 -r tunnel://127.0.0.1:3389
```

**Comment by sarpedon333** [comment]
@qwj working like a charm.. 🥇 
Cheers!
