### ISSUE TITLE
Socket server to socket server tunnel

### ISSUE THREAD

**Issue by davidalo** [qwj/python-proxy#110]
Hi everyone,

I have been trying this module and it is very useful. I would like to ask if anyone has been able to create a Server to Server tunnel. I would like to create a new TLS server which listens and when it receives a connection, it opens a TCP/TLS socket which also listens for connections.

Is this feature available? I will take a deeper look at the code this weekend, but any help will be highly appreciated!

**Comment by qwj** [comment]
Hi,

This feature is available with "backward proxy". You can find examples in the README.rst "backward proxy" chapter.

**Comment by davidalo** [comment]
Hi @qwj .

Thanks for your reply. I don't know what I was doing bad, but you are right, it works using CLI. 

I will work on it using the Python API this weekend but, for now, I close this issue.
