### ISSUE TITLE
Daemon mode seems not to work

### ISSUE THREAD

**Issue by marearth** [qwj/python-proxy#120]
When I transformed traffic from http to socks, connection was fine when running in foreground.However, program could not work when running in the Daemon mode,it did not establish listening port any more. Here is the code:  
`#!/bin/bash
# chkconfig: 345 99 10
# Description: auto start pproxy server
#
DAEMON=/home/richard/.local/bin/pproxy
test -x $DAEMON || exit 1 
case "$1" in
 'start')
   $DAEMON -l socks5://0.0.0.0:1081#test:nnn -r http://192.168.100.88:1080  -vv  --daemon;;
 'stop')
   kill -9 $(lsof -i -P | grep -i "listen" | grep pproxy | awk '{print $2}');; 
 'restart')
   kill -9 $(lsof -i -P | grep -i "listen" | grep pproxy | awk '{print $2}');sleep 3;$DAEMON -l socks5://0.0.0.0:1081#test:nnn -r http://192.168.100.88:1080  -vv  --daemon;;
 *)
   echo "Usage: $0 {start|stop|restart}";exit 1
esac`

**Comment by qwj** [comment]
Try remove "-vv" parameter in the command line. It may prevents the daemonized program to start.

**Comment by marearth** [comment]
> Try remove "-vv" parameter in the command line. It may prevents the daemonized program to start.

Thanks.Problem is solved. Your repository is useful for some people.  More detailed usage document will be favored.
