### ISSUE TITLE
ssl.c error occurs with HTTPS proxy on Ubuntu 20.04, OpenSSL 1.1.1f

### ISSUE THREAD

**Issue by shirt-dev** [qwj/python-proxy#124]
On a fresh install of Ubuntu 20.04 with OpenSSL 1.1.1f, I get the following error while using http+ssl:// proxies. The proxy works, but slows down toward the end of the connection.
```
[SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2750)
```

**Comment by qwj** [comment]
Can you print the versions of Python and python-proxy?

**Comment by shirt-dev** [comment]
Python 3.9.3
pproxy 2.7.7

**Comment by shirt-dev** [comment]
Appears to be an issue with the proxy server itself, thanks for the great work on this!
