### ISSUE TITLE
problem with command

### ISSUE THREAD

**Issue by kunger97** [qwj/python-proxy#128]
In this scene 
`PublicPort(server2) ---via WS+TLS tunnel---> privatePort(server1)`
(i want server1's private port can be access publicly on server2's public port)

I tried use this command on server1
`pproxy -l ws+ssl://:2083 -r tunnel://127.0.0.1:2053 --ssl somecert.pem,somekey.key`

and this command on server2

`pproxy -l tunnel://:33206 -r ws+ssl://server1:2083`

that not working, i may use wrong protocols or command please give me some help.

**Comment by Jonney** [comment]
Try this:

server1
pproxy -l ws+ssl://:2083 --ssl somecert.pem,somekey.key

server2
pproxy -l tunnel{127.0.0.1:2053}://:33206 -r ws+ssl://server1:2083

**Comment by kunger97** [comment]
it shows
`Unknown remote protocol from server1's IP`
on server 2
and shows
`Unsupported protocol from server2‘s ip`
on server1
