### ISSUE TITLE
Run Problem ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by mengyyy** [qwj/python-proxy#13]
Win10 
Python 3.6.4
pproxy 1.7.3  and 1.8.5

> Traceback (most recent call last):
>   File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\Python36\Scripts\pproxy.exe\__main__.py", line 5, in <module>
>   File "c:\program files\python36\lib\site-packages\pproxy\server.py", line 2, in <module>
>     from . import proto
>   File "c:\program files\python36\lib\site-packages\pproxy\proto.py", line 1, in <module>
>     import asyncio, socket, urllib.parse, time, re, base64, hmac, struct, hashlib, fcntl, io
> ModuleNotFoundError: No module named 'fcntl'

And install form pip also has problem:

> Traceback (most recent call last):
>   File "setup.py", line 19, in <module>
>     long_description    = read('README.rst'),
>   File "setup.py", line 6, in read
>     return fp.read()
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 2840: illegal multibyte sequence

This is because  `long_description   = read('README.rst')` in _setup.py_

**Comment by qwj** [comment]
Hi, the first problem was fixed in 1.8.6
The second problem is the text encoding issue. You may check if the default encoding in the python environment is utf-8.

**Comment by qwj** [comment]
The second problem was also fixed by forcing encoding='utf8' in setup.py

**Comment by mengyyy** [comment]
Now all is OK.
