### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bryanhelmig** [qwj/python-proxy#14]
The assumed default license is "all rights reserved". Most Python projects are BSD / MIT / ISC / etc...

https://docs.python-guide.org/writing/license/

Curious if you'd consider applying a license here?

**Comment by qwj** [comment]
MIT license was uploaded
Thanks for the reminding

**Comment by jiamo** [comment]
License file contain wrong name?

**Comment by qwj** [comment]
> License file contain wrong name?

fixed. sorry for that
