### ISSUE TITLE
http proxy fail for  pproxy -l http://:9000/ -r http://httpbin.org/ -v

### ISSUE THREAD

**Issue by chen19901225** [qwj/python-proxy#167]
use command ` pproxy -l http://:9000/ -r http://httpbin.org/ -v` or `pproxy -l http+httponly://:9000 -r http+httponly://httpbin.org/ -v`

then `curl 'http://127.0.0.1:9000/'` get `curl: (52) Empty reply from server` and command log show `Serving on :9000 by http,httponly 
404 GET / from 127.0.0.1`

does i use is uncorrected?

**Comment by Thoufak** [comment]
How did you solve this?
