### ISSUE TITLE
QUIC tunnel

### ISSUE THREAD

**Issue by mosajjal** [qwj/python-proxy#20]
Something like this has already been done in Go:

```https://github.com/liudanking/quic-proxy```

but I think it'll need a couple extra libraries. It's exteremely fast and reliable and it's somewhat undetected under a lot of Firewalls :)

**Comment by qwj** [comment]
It is quite different and don’t have much in common.

Alireza Mosajjal <notifications@github.com>于2018年12月23日 周日12:51写道：

**Comment by mosajjal** [comment]
I know, I'll try to create a standalone one based on `asyncio` and maybe we'll port it back to this project as well. I wanted to let you know that I've tested QUIC and it's extremely fast.
