### ISSUE TITLE
Direct API usage

### ISSUE THREAD

**Issue by devinrsmith** [qwj/python-proxy#22]
I'd like to use python-proxy inline in my existing python application. It seems like I could built it up myself from pproxy, but I'd be replicating a lot of the functionality in server.main. It would be great if there was a developer friendly function `pproxy` that took arguments and returned a coroutine that did all the proxying.

Then the server.main would look something like:
```python
def main():
  ...
  args = parser.parse_args()
  loop = asyncio.get_event_loop()
  loop.run_until_complete(pproxy(args))
  loop.close() 
```

I'm not sure if this works well w/ your architecture - but it would be very handy for my use case!

Cheers!

**Comment by qwj** [comment]
Good idea. Will consider this feature next version

Devin Smith <notifications@github.com>

**Comment by qwj** [comment]
Server API feature was added in v2.0.3
Please check README or tests/api_server.py example

**Comment by devinrsmith** [comment]
You are AWESOME. Thanks a bunch - it's working! :D
