### ISSUE TITLE
wrong pip version

### ISSUE THREAD

**Issue by Pezhvak** [qwj/python-proxy#25]
i've tried to install your package with pip3 and pip, both installs version 1.2.2

**Comment by qwj** [comment]
pproxy supports Python 3.6 or above.
Python3.5 or lower can still install pproxy with very old version "1.2.2"

**Comment by Pezhvak** [comment]
this is from my pip --version

pip 18.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

it's python 3.6 and installs 1.2.2, do in need to upgrade?

**Comment by qwj** [comment]
Can you paste pip's output here?

```
pip install --upgrade --no-cache-dir pproxy
```
