### ISSUE TITLE
bug in providing ipv6 binding (SOCKS)

### ISSUE THREAD

**Issue by Pezhvak** [qwj/python-proxy#26]
when running proxy with the following arguments socks gives this error: getsockaddrarg() takes exactly 2 arguments (4 given) from 95.X.X.X

pproxy -l http+socks5://93.X.X.X:9000/@00:e:0:0:0:0:edaf:80ef#user:pass -v

**Comment by qwj** [comment]
Old version pproxy doesn't have this syntax @xxx. Can you have a try with the latest pproxy with Python 3.6 or above?

**Comment by Pezhvak** [comment]
i actually downloaded the project and ran it without pip, the issue is still there and python version is 3.6. it does not happen with http proxy, i get this with socks5, maybe others too but i'm sure about socks5

**Comment by Pezhvak** [comment]
i just upgraded my python to 3.7, ran it again and problem is still there

**Comment by qwj** [comment]
thanks, I will investigate this issue

**Comment by qwj** [comment]
I don't have IPv6 test environment on hand.
I added a new patch to make sure use ipv6 when bind on ipv6 address.
can you try v2.0.8 to see if it works now?

**Comment by Pezhvak** [comment]
hi, the error message is changed to this:
[Errno -6] ai_family not supported from 95.X.X.X

**Comment by qwj** [comment]
this message occurred only when the python is built without IPv6 support.
if the python binary is built from source, make sure to add "--enable-ipv6"

**Comment by Pezhvak** [comment]
i've reinstalled python 3.7 with `--enable-upv6` flag, still same error, i also tried with python 3.6 which was installed via yum command, same error again, any suggestion?

**Comment by Pezhvak** [comment]
if you still need an environment with ipv6 i might be able to provide one so you can test it for yourself, please do email me at pezhvakimv@gmail.com so i can send you the information
