### ISSUE TITLE
Statically linked binary release

### ISSUE THREAD

**Issue by mosajjal** [qwj/python-proxy#28]
Hi, I managed to get a working statically linked binary for `pproxy` [here](https://n0p.me/bin/pp.py3). Do you think it's advisable to put that binary in the release section of the project? It works very well and doesn't depend on system's Python version. Most older Linux distros don't have python 3.6 so the binary will work just fine

**Comment by qwj** [comment]
pproxy is cross-platform, can be run on Linux/Mac/Windows
I think we don't need to provide binary for all platforms.
Thanks for the distribution package. 👍
