### ISSUE TITLE
pycryptodome and sshtunnel interfere with each other

### ISSUE THREAD

**Issue by mosajjal** [qwj/python-proxy#31]
As you know, `asyncssh` requires `pycrypto` to be installed. `pycryptodome`'s documentation says:

One must avoid having both PyCrypto and PyCryptodome installed at the same time, as they will interfere with each other.

So we can't have both `sshtunnel` and C accelerations at the same time. Any workarounds?

**Comment by qwj** [comment]
asyncssh requires **cryptography**, different library from **pycrypto**.
**cryptography** and **pycryptodome** can be used together without problems.
😄

**Comment by qwj** [comment]
I am thinking of using only one of the two libraries to simplify the dependencies.
It may be good to switch from **pycryptodome** to **cryptography** in our project.

**Comment by mosajjal** [comment]
can we have some benchmarks comparing `pycryptodome` and `cryptography`?

**Comment by qwj** [comment]
there is an old benchmark two years ago: http://nlitsme.github.io/posts/benchmarking-some-python-crypto-libraries/

**Comment by mosajjal** [comment]
I know that `pycryptodome` and `pycrypto` are drop-in replacements for one another. But I think using `cryptography` instead of `pycryptodome` requires some modifications in the code, right?

**Comment by qwj** [comment]
sure, code should be modified and more tests should be done.

**Comment by mosajjal** [comment]
I'm working on changing the Docker image from Alpine to Tinycore to have `glibc` to provide ssh tunnel as well as crypto acceleration. After that, I'll try to write some scripts to benchmark crypto speed. I'm guessing you want to keep things as lean as possible (so am I) so we'll think of something after the benchmark

**Comment by qwj** [comment]
thanks for the work. waiting for result of your benchmark. 👍

**Comment by mosajjal** [comment]
https://github.com/mosajjal/python-crypto-benchmark

take a look at this project. Very basic benchmarks. Let me know if there's anything I can help with. My understanding is, cryptography is just as good maybe even better.

**Comment by qwj** [comment]
really appreciate your help. as the result suggests, I am planning to move to **cryptography** soon.

**Comment by qwj** [comment]
after several days of investigation, cryptography design is redundant.
for example, it has a design of changing backend, and now it is obsolete. 
you should call get_default_backend() every time.
many useful apis have been labeled "hazardous materials"
so I don't think it is the right time to move from **pycryptodome** to **cryptography**
let's wait if there is some important reason in the future.

**Comment by mosajjal** [comment]
I agree. We could wait for a couple of months to see if any crypto library with Rust backend gets introduced as well
