### ISSUE TITLE
ipv6 issue

### ISSUE THREAD

**Issue by Pezhvak** [qwj/python-proxy#32]
when i try to `pproxy -l http+socks5://93.11.80.25:9005/@2a00:e60:4000:100:8000:0:f5e8:2b73#user:pass -v`

it gives the following error: [Errno -6] ai_family not supported from 79.127.80.11 (this is connected client IP)

it seems server gets confused, the bind ip is IPv6 but user is getting connected through IPV4:9005.

**Comment by qwj** [comment]
"ai_family not supported" is shown only when Python binary doesn't build with ipv6 support

**Comment by Pezhvak** [comment]
dear sir, it was working before #2efed7e without a problem, i'm still working with that commit. the problem was something else and you misunderstood, the problem isn't IPV6 on the server, let me demonstrate to be clear:

![diagram](https://user-images.githubusercontent.com/3134479/55462196-74758a80-560b-11e9-8201-aeace0552b4d.jpg)

i have thousands of IPv6 on server, and each user is using one of the IPv6s on the server for connecting to the internet (HTTP for this example).

you have forced proxy to use IPv6 for communicating with client. which they don't have. that's why they are connecting to server by IPv4:port_number (port forwarding to use IPv6 through IPv4 on server)

that was working with HTTP before #2efed7e, the problem was on SOCKS5. it wasn't respecting IPv6 binding parameter. now neither works.

for example if you connect to 110.115.22.40:9000 in your firefox, your ip (browsing the internet by firefox) will be 2001:0:9d38:6ab8, if you connect (another user perhaps) 110.115.22.40:9001 your public ip will be 2001:0:9d38:6ac1 (different IPv6).

hope i made my self clear. what you did wasn't the issue i was referring to. it even broke the code that was working fine with HTTP as well. the issue is on SOCKS, when you run the given command `http+socks5://93.11.80.25:9005/@2a00:e60:4000:100:8000:0:f5e8:2b73#user:pass -v` before commit #2efed7e, http would use ipv6 as the outgoing ip to internet on the server, but socks would use IPv4 and completely ignore the binding parameter.

**Comment by qwj** [comment]
I have reverted the commit 2efed7eeadaf0debff558e1fe19aa842b91fa793 and upgraded a new version v2.1.3. Can you see if that fix the ipv6 problem?

**Comment by Pezhvak** [comment]
yes, it's working again, here's output of the command:

http 5.250.108.41:11903 -> incoming.telemetry.mozilla.org:443
http 5.250.108.41:11904 -> incoming.telemetry.mozilla.org:443
http 5.250.108.41:11905 -> incoming.telemetry.mozilla.org:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11906 -> incoming.telemetry.mozilla.org:443
http 5.250.108.41:11907 -> incoming.telemetry.mozilla.org:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11908 -> incoming.telemetry.mozilla.org:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11909 -> incoming.telemetry.mozilla.org:443
http 5.250.108.41:11910 -> incoming.telemetry.mozilla.org:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11911 -> incoming.telemetry.mozilla.org:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11912 -> incoming.telemetry.mozilla.org:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11969 -> securetoken.googleapis.com:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11988 -> www.google.com:443
http 5.250.108.41:11991 -> tiles.services.mozilla.com:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11992 -> tiles.services.mozilla.com:443
http 5.250.108.41:11993 -> safebrowsing.googleapis.com:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:11994 -> ocsp.pki.goog:80
http 5.250.108.41:11995 -> www.google.com:443
http 5.250.108.41:12005 -> tiles.services.mozilla.com:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:12012 -> www.google.com:443
http 5.250.108.41:12017 -> www.gstatic.com:443
http 5.250.108.41:12023 -> id.google.com:443
http 5.250.108.41:12024 -> www.gstatic.com:443
http 5.250.108.41:12026 -> snippets.cdn.mozilla.net:443
getsockaddrarg() takes exactly 2 arguments (4 given) from 5.250.108.41
http 5.250.108.41:12028 -> encrypted-tbn1.gstatic.com:443
http 5.250.108.41:12030 -> encrypted-tbn3.gstatic.com:443
http 5.250.108.41:12029 -> encrypted-tbn3.gstatic.com:443
http 5.250.108.41:12031 -> encrypted-tbn1.gstatic.com:443
http 5.250.108.41:12033 -> img-getpocket.cdn.mozilla.net:443
http 5.250.108.41:12035 -> adservice.google.com:443
http 5.250.108.41:12038 -> googleads.g.doubleclick.net:443


as you can see sometimes it outputs "getsockaddrarg() takes exactly 2 arguments (4 given)"

and now we're back to #26 SOCKS has the problem but at least HTTP is working again

**Comment by qwj** [comment]
can you make sure the python binary on the server was downloaded from official website? or built with --enable-ipv6 option?

**Comment by Pezhvak** [comment]
yes last time you suggested the same thing and i installed python from source with the given flag, and also i can provide you IPv6 server to test and make sure for yourself

**Comment by qwj** [comment]
okay, please give me the access to your server. I can investigate this issue on your server.

**Comment by Pezhvak** [comment]
can you provide me an email address to send you the information? (for the sake of security)

**Comment by qwj** [comment]
qianwenjie@gmail.com
thanks

**Comment by Pezhvak** [comment]
information is sent, i'm available if you needed anything else. thank you!

**Comment by qwj** [comment]
seems like I have fixed the issue. 
a new version v2.1.4 is available.
can you have a try if it works on the production server?

**Comment by Pezhvak** [comment]
hi, it seems the previous error message is gone, however this is what i get now on production server

[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15731 -> test-ipv6.com:443
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15737 -> csi.gstatic.com:443
http 5.250.108.41:15740 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15742 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15743 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15744 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15745 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15746 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15747 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15749 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15750 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15751 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15755 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15756 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15757 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15758 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15760 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15761 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15764 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15765 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15766 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41
http 5.250.108.41:15767 -> whatismyip.host:80
[Errno -2] Name or service not known from 5.250.108.41


5.250.108.41 is client ip, not the server ip.

this is how i test on client side:

curl --proxy SERVER_IP:9000 https://ifconfig.co

or for SOCKS:

curl --socks5 SERVER_IP:9000 https://ifconfig.co

for socks5 i get the following error in server output:

[Errno 111] Connect call failed ('::1', 80, 0, 0) from 5.250.108.41

**Comment by qwj** [comment]
ipv6 dns lookup fails for test-ipv6.com and whatismyip.host 
they doesn't have AAAA domain for ipv6

$ dig AAAA whatismyip.host
;whatismyip.host.		IN	AAAA
no answer

$ dig whatismyip.host
whatismyip.host.	255	IN	A	34.233.244.94

**Comment by qwj** [comment]
the problem is, if you insists to bind on ipv6 socket, the remote domain should have ipv6 address with AAAA domain record.
you can try google.com instead. seems that many domain doesn't have AAAA domain record, so the dns lookup fails in ipv6 way.

**Comment by Pezhvak** [comment]
sure. i've used https://ifconfig.co as well which is working fine:

curl —-proxy SERVER_IP:9000 https://ifconfig.co

**Comment by Pezhvak** [comment]
but it gives the following error:
Errno 111] Connect call failed ('::1', 80, 0, 0) from 5.250.108.41

previously it would show the ipv6 for http proxy, but SOCKS5 would not work at all. now neither works

**Comment by qwj** [comment]
can you try the test server?
I am running a script "pproxy -l http+socks5://212.227.174.168:9000/@2001:8d8:1800:8088::1b -vv"
you can make connection to 212.227.174.168:9000 to find if it works

**Comment by Pezhvak** [comment]
i just made a call. can you see the error on the console?
i think you are testing the proxy from the server (which has ipv6 on it) can you try from your own computer by running:

`curl --proxy 212.227.174.168:9000 https://ifconfig.co`

or for socks

`curl --socks5 212.227.174.168:9000 https://ifconfig.co`

**Comment by qwj** [comment]
[root@localhost ~]# curl --socks5-hostname 212.227.174.168:9000 https://ifconfig.co
2001:8d8:1800:8088::1b
[root@localhost ~]# curl --proxy 212.227.174.168:9000 https://ifconfig.co
2001:8d8:1800:8088::1b

**Comment by qwj** [comment]
you should use --socks5-hostname instead of --socks5 for ipv6
"curl --socks5" resolves the domain locally and give a wrong IPv4 address to the remote proxy
"curl --socks5-hostname" would keep the hostname to the remote proxy

**Comment by Pezhvak** [comment]
you are right, i executed your code on my production server and it works, client should have IPv6 in order to be able to get connected to server. the case is that we are using 212.227.174.168:9000 because we know client doses not have IPv6 only server has one, can you run it from your own terminal (not the server?)

**Comment by Pezhvak** [comment]
this is what i get from executing your command:

`
curl --socks5-hostname 212.227.174.168:9000 https://ifconfig.co
curl: (7) Unable to receive initial SOCKS5 response.
`
this is from my local machine (doesn't have IPv6)

**Comment by Pezhvak** [comment]
dear sir, it seems to be working now can you commit so i can run it in my production server?

**Comment by qwj** [comment]
I run on my laptop without ipv6, get the same correct result.

$ curl --proxy 212.227.174.168:9000 https://ifconfig.co
2001:8d8:1800:8088::1b
$ curl --socks5-hostname 212.227.174.168:9000 https://ifconfig.co
2001:8d8:1800:8088::1b

we don't need ipv6 support on the client. is there any problem in the curl program in your production server?

**Comment by qwj** [comment]
the new version v2.1.4 is available already
you can upgrade and try 😄

**Comment by Pezhvak** [comment]
i confirm, this is working now, WOW THANK YOU VERY VERY MUCH.
is it gonna work with shadowsocks as well?

**Comment by qwj** [comment]
thank you for the test environment
I have logged out and please change the password

**Comment by Pezhvak** [comment]
thank you sir 🙏 ^_^

**Comment by qwj** [comment]
it supports many protocols include shadowsocks.
you can see the document in README.rst
