### ISSUE TITLE
Usage with aiohttp ?

### ISSUE THREAD

**Issue by jekel** [qwj/python-proxy#33]
Hello
My use case is - to configure Connection with several relay socks proxies and to use it with aiohttp - how it is possible?
thanks

**Comment by qwj** [comment]
API class **Connection** can't be used with aiohttp together now
I have read the document of aiohttp Connector API
It is not possible to put streams in them

**Comment by jekel** [comment]
May be there is another solution how to use them together? 
Or is it planned to implement aiohttp support later?

**Comment by qwj** [comment]
can you describe the use case that aiohttp support is required?

**Comment by jekel** [comment]
I have application which uses async aiohttp.client to connect to external web resources, so, now, i'm trying to find some solution to use socks proxy chain with it.. and i have found your project

**Comment by qwj** [comment]
a workaround is to use UnixConnector in aiohttp.client
and running pproxy in server mode listen in unix socket
