### ISSUE TITLE
DAT file support for outgoing traffic

### ISSUE THREAD

**Issue by mosajjal** [qwj/python-proxy#35]
Hi, 

Do you think it's possible to write a parser for DAT files and add their configuration to `pproxy` for remote hosts (-r)? DAT files have their own standard formatting for host whitelisting and blacklisting so it would be a great integration

**Comment by qwj** [comment]
Hi, do you have the specification of DAT file formatting?

**Comment by mosajjal** [comment]
DAT file uses the same syntax as `PAC`. I understand `pproxy` can publish it's configuration via a `PAC` file, but reading `PAC` file and adding it into configuration is not part of it, right? There's a library called `pypac` that reads and digests a `PAC` file and gives you the related HTTP proxy for each URL.

**Comment by qwj** [comment]
Interpreting PAC is not an easy thing. PAC file is coded in Javascript. Additional library (dukpy,pyv8,js2py) is required to execute the PAC(Javascript) file.
pproxy supports hostname whitelisting/blacklisting by regular expression rules.
If you think PAC parsing is a strong need, maybe we can make a branch or add plugin support for host filter.

**Comment by mosajjal** [comment]
I know how PAC works, but `DAT` files on their own should be easy to interpret. [pypac](https://github.com/carsonyl/pypac) does this in pure-python and gives out a proxy for each URL you ask it. So maybe add it as an optional dependency and the user could replace `-r` in pproxy with `-rpac` with the path to the `DAT` file?
