### ISSUE TITLE
UDP Connections do not seem to work

### ISSUE THREAD

**Issue by muelli** [qwj/python-proxy#39]
I have a simple SOCKS5 client which sends a UDP ASSOCIATE request.

I have expected python-proxy to let me establish UDP connections.
However, I get "Unknown SOCKS protocol" back. The code seems to assume that the client sends a regular TCP connection request:

https://github.com/qwj/python-proxy/blob/7134d6809c275e372e0acec7c669d2c2ff2cb2df/pproxy/proto.py#L201

Are UDP connections out of scope?

**Comment by qwj** [comment]
Sorry, Socks5 UDP bind is not supported. It was documented in the README.rst as not supported feature.

**Comment by muelli** [comment]
> It was documented in the README.rst as not supported feature.

by saying it *was* do you mean that this documentation is gone? Because I can't find anything related to establishing UDP connections with a target host in the readme.

**Comment by qwj** [comment]
Sorry, the README is limited because there are so many features to document.
