### ISSUE TITLE
是否考虑支持kcptun?

### ISSUE THREAD

**Issue by txdywy** [qwj/python-proxy#4]
😁

**Comment by qwj** [comment]
kcptun比较底层，还需要再考虑一下怎么支持

**Comment by qwj** [comment]
经过考察应该是啥都不用改就支持kcptun
- Client
    pproxy: pproxy -r ss://localhost:8388
    KCPTun: ./client_darwin_amd64 -r "KCP_SERVER_IP:4000" -l ":8388" -mode fast2
- Server
    KCPTun: ./server_linux_amd64 -t "TARGET_IP:8388" -l ":4000" -mode fast2
    pproxy: pproxy -i ss://localhost:8388
