### ISSUE TITLE
Do not patch builtin classes

### ISSUE THREAD

**Issue by Lonami** [qwj/python-proxy#43]
https://github.com/qwj/python-proxy/blob/dc0279c00d650fef52c7d3fe4fd07bcfc5589b24/pproxy/server.py#L10-L12

It is very prone to breaking and should not be done. Consider sub-classing or making a proxy object instead. If anyone else were to do the same, this would break.

**Comment by qwj** [comment]
This is a good suggestion. Patching builtin class is the easiest way to do this job, and pproxy is mostly used standalone.
