### ISSUE TITLE
Several asyncio.ensure_future are never awaited

### ISSUE THREAD

**Issue by Lonami** [qwj/python-proxy#44]
One should not "fire and forget" futures to work as "background tasks". This is very much like launching a thread and forgetting about it, when you probably should join it back at some point. This makes the code harder to reason about. One must properly `await` them, at some point in the future, and they're not even saved anywhere. See https://vorpus.org/blog/notes-on-structured-concurrency-or-go-statement-considered-harmful/ for a good reasoning and their designed "nurseries" as to why this is good.

**Comment by qwj** [comment]
The created background tasks would handle their lifecycle themselves. Nursery is a good idea, but I don't think it should be widely accepted.

**Comment by Lonami** [comment]
Why should it not be widely accepted? If those background tasks fail, there will be no way to react accordingly. At best it will log an error.

**Comment by qwj** [comment]
Because we doesn’t care about whether the background task fails.

Lonami <notifications@github.com>
