### ISSUE TITLE
Serve backward / reverse connection in Python code

### ISSUE THREAD

**Issue by TensorTom** [qwj/python-proxy#48]
I am trying to start from the example code to achieve a dynamic reverse proxy setup but having difficulty figuring out how to do it. Server is behind NAT. I need Server to connect to CentralServer. Then, CentralServer to open a port so that browser clients can tunnel through Server behind NAT:

```
<-- WWW <-- ServerBehindNAT <--> CentralServer <-- BrowserClient1
                                               <-- BrowserClient2
```

**Comment by TensorTom** [comment]
Can you please show me how the backwards example will look in python?

**Comment by qwj** [comment]
Hi, the easiest way is to use standalone program pproxy in the README example.
The library API for backward proxy is not prepared now.

**Comment by TensorTom** [comment]
Thanks for the reply. What is wrong with it? I had posted the code here: https://stackoverflow.com/questions/57247037/reverse-proxy-with-pproxy-via-python-api

I was going to use it for a big project with many servers.

**Comment by TensorTom** [comment]
I have deleted the stack question. It was this:

I am trying to use the [pproxy library][1] for a reverse proxy setup. At the bottom of the Github readme are example commands for a reverse proxy setup as follows:

To run on client: `pproxy -l http://:8080 -r http+in://:8081 -v`

To run on proxy behind NAT: `pproxy -l http+in://client_ip:8081`

This works good. I am able to test in my browser but if I try the same thing in the pproxy Python API, it doesn't work:

**client.py**:
```
import asyncio
import pproxy

central_relay = pproxy.Server('http+in://127.0.0.1:8081')

args = dict(verbose=print)

loop = asyncio.get_event_loop()
handler = loop.run_until_complete(central_relay.start_server(args))
try:
    loop.run_forever()
except KeyboardInterrupt:
    print('exiting')

handler.close()
loop.run_until_complete(handler.wait_closed())
loop.run_until_complete(loop.shutdown_asyncgens())
loop.close()
```

**server.py**
```
import asyncio
import pproxy


browser = pproxy.Server('http+socks5://:8080')
proxy_server = pproxy.Connection('http+in://8081')

args = dict(verbose=print,
            rserver=[proxy_server])
loop = asyncio.get_event_loop()

browser_handler = loop.run_until_complete((browser.start_server(args)))
try:
    loop.run_forever()
except KeyboardInterrupt:
    print('exiting on interrupt')

browser_handler.close()
loop.run_until_complete(browser_handler.wait_closed())
loop.run_until_complete(loop.shutdown_asyncgens())
loop.close()
```

I have also tried mix-matching the code versions I came up with with the CLI commands that I know do work but I can't figure it out.

  [1]: https://github.com/qwj/python-proxy

**Comment by qwj** [comment]
The backward proxy mode is more complex than straightforward proxy. Client should listen for connection, and server should connect to client backward. The API library is not prepared for these handling.
