### ISSUE TITLE
同主机多IP情况下，自身当独立代理服务器希望能采取适配性的IP策略

### ISSUE THREAD

**Issue by fun0gs** [qwj/python-proxy#5]
__init__.py代码53行可以改为：
```python
server_ip = writer.get_extra_info('sockname')
if server_ip != '127.0.0.1':
    wait_connect = asyncio.open_connection(host=host_name, port=port, local_addr=(server_ip, 0))
else:
    wait_connect = asyncio.open_connection(host=host_name, port=port)
```

不太方便使用pr，希望可以改成类似这种，可以达到访问192.168.1.100使用100代理外网，访问192.168.1.101使用101代理外网，在单主机多IP的情况下特别方便，也可以加个argparse参数控制:-)

**Comment by fun0gs** [comment]
```python
if viaproxy:
    ...
else: #这里
```

**Comment by qwj** [comment]
感谢建议，我看看怎么改比较好

**Comment by qwj** [comment]
1.4.2增加了一个 URI 的新语法。比如用下面语法可以做到你希望的效果：
$ pproxy -i http://:8000/@in
假如想要不管哪个interface来的traffic都bind 一个ip：
$ pproxy -i http://:8000/@192.168.1.10
还可以给远端服务器指定用哪个bind ip去访问：
$ pproxy -i http://:8000 -r ss://192.168.1.15:1234/@192.168.1.10
希望能用得上。

**Comment by fun0gs** [comment]
我pip更新了一遍，在多ip的服务器上很好用:-)，不过文档你没更新喔

**Comment by qwj** [comment]
文档也更新了，就是写的比较乱不太好找，在URI syntax里加了一部分，最后的Example也加了个例子。感谢你的建议

**Comment by fun0gs** [comment]
这不就是开源精神😄，我找了很多工具，还是最喜欢用你这个工具了

**Comment by qwj** [comment]
谢谢你，希望帮我多推荐给更多人哈
