### ISSUE TITLE
Redirect to different proxies depending on auth

### ISSUE THREAD

**Issue by agustinjch** [qwj/python-proxy#52]
Hi!

I'd like to set a proxy server, over the same IP, i.e (localhost:9090), but with different authentications to redirect the traffic over one or another proxy. Let's say 

`http://test1:test1@localhost:9090/` will redirect to proxy `http://a.b.c.d:1234` `http://test2:test2@localhost:9090/` will redirect to proxy `http://e.f.g.h:1235`

I'm new in this, so I don't actually know if this should be done here, or in a server (apache, nginx, etc) to redirect the traffic to one or another proxy server depending on the auth

I have read the doc, but I can't find anything like it

In case it can be done straight with python-proxy , what's the way?

Thanks in advance

**Comment by agustinjch** [comment]
I figured it out myself, so I'm closing the issue

I just had to change in the proto.py the Basic authentication handling, and the schedule function in server.py

Amazing library BTW

**Comment by MaxPlayBR** [comment]
Hello, would it be possible to start the proxy server and redirect all requests to another proxy?
