### ISSUE TITLE
add network throttling feature

### ISSUE THREAD

**Issue by tarekziade** [qwj/python-proxy#54]
Would you be interested in adding a plugin that does network throttling ?

That is:
- limit the bandtwidth
- add delays 

I am using this to mimic network conditions to test browser page loads. I've implemented it using a simple port forwarder + socks5 server ar https://github.com/tarekziade/tinap

But your proxy is much better as it implements many protocols!

I guess most of the code that does this is here: https://github.com/tarekziade/tinap/blob/master/tinap/throttler.py and should be simple to refactor as a pproxy plugin

Let me know!

**Comment by qwj** [comment]
Hi, I think there is a very simple implementation: add a throttler port forwarder in front of pproxy. For example, a port forwarder map port 1080 to localhost:1081, and pproxy listens on localhost:1081
