### ISSUE TITLE
Remote http+ssl not working

### ISSUE THREAD

**Issue by dannyeuu** [qwj/python-proxy#56]
How to use properly remotes https://aa.bb.cc.dd proxies?

I have the following result:
``` bash
[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:777) from 127.0.0.1
```
or 
``` bash
Unsupported protocol from 127.0.0.1
```

And my python request with this proxy listening
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='domain.com', port=443): Max retries exceeded with url: /index (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
```

**Comment by qwj** [comment]
You can use -r http+ssl:// to connect remote https proxy.
Can you paste the parameters or server configuration?

**Comment by dannyeuu** [comment]
Thanks for your reply @qwj, 
We are using `http+ssl://aa.bb.cc.dd:1234`  that occurs this error
