### ISSUE TITLE
HTTP proxy via CONNECT method should return 200 after connect to target host

### ISSUE THREAD

**Issue by HopeForToday** [qwj/python-proxy#62]
Request like this:

```
CONNECT api.github.com:443 HTTP/1.1
Host: api.github.com:443
...
```

Proxy server should connect to `api.github.com` first, instead of just return `200` regardless of whether we can connect to `api.github.com`.

REF: [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.6)

**Comment by qwj** [comment]
Thanks!
I will fix this issue next version.
