### ISSUE TITLE
Header drops 4 characters

### ISSUE THREAD

**Issue by daspri** [qwj/python-proxy#64]
pproxy/proto.py 

line 274:
```
lines, data = data.split(b'\r\n\r\n', 1)
headers = lines[:-4].decode().split('\r\n')
```
The data.split removes the '\r\n\r\n', therefore splicing off [:-4] is not needed.  It cuts off last 4 characters of a valid header.

**Comment by qwj** [comment]
Thanks for the help! It is a serious bug.
I have fixed in v2.2.4
