### ISSUE TITLE
Fails to proxy http

### ISSUE THREAD

**Issue by daspri** [qwj/python-proxy#65]
Proxy works with both https and http, & the proxy works in chrome.
```
curl --proxy-insecure -x https://proxy:9002 -A "" "https://httpbin.org/headers" -v
curl --proxy-insecure -x https://proxy:9002 -A "" "http://httpbin.org/headers" -v
```

Proxy works with python-proxy https:
```
pproxy -vv -l http://127.0.0.1:3136 -r "http+ssl://proxy:9002"
curl -x http://127.0.0.1:3136 -A "" "https://httpbin.org/headers" -v
```
Doesn't work with http:
```
curl -x http://127.0.0.1:3136 -A "" "http://httpbin.org/headers" -v
```
Squid: Invalid URL
But fixing the "newpath" in proto.py "HTTP parse" still returns an error

Note: Edited out proxy IP, can send if needed.

**Comment by qwj** [comment]
With "-r http://", pproxy connect to remote http proxy using CONNECT.
With "-r httponly://", pproxy connect to remote http proxy using GET/POST/...
This special remote http proxy only accepts GET/POST for http request.
So the following curl command will report 403 response. (add -p in curl)

`curl --proxy-insecure -p -x https://proxy:9002 -A "" "http://httpbin.org/headers" -v`

You can specify -r httponly:// in pproxy to use GET/POST/... for the remote proxy.

`pproxy -vv -l http://127.0.0.1:3136 -r "httponly+ssl://proxy:9002"`

**Comment by daspri** [comment]
How to get one pproxy instance to handle both http and https? 
I think 'rules' are for hosts only, not schemes or paths?

Works: 
```
curl --proxy-insecure -x https://proxy:9002 -A "" "http://google.com" -v -L
curl --proxy-insecure -x https://proxy:9002 -A "" "http://microsoft.com" -v -L
```

Doesn't work:
```
pproxy -vv -l http://127.0.0.1:3136 -r "httponly+ssl://proxy:9002"
curl -x http://127.0.0.1:3136 -A "" "http://google.com" -v -L
curl -x http://127.0.0.1:3136 -A "" "http://microsoft.com" -v -L
```

**Comment by qwj** [comment]
Currently there is no such rules to handle both http and https.
pproxy is not only a http proxy.
If served in other protocol such as socks5, shadowsocks, there is no way to get the scheme information from client.
In general we must assume the remote http proxy accepts CONNECT for any ports (both 80, 443).

**Comment by qwj** [comment]
An alternative way to bypass this issue is to use tunnel instead of http:

`pproxy -vv -l tunnel://127.0.0.1:3136 -r "tunnel+ssl://proxy:9002"`

**Comment by daspri** [comment]
Thank you.  This way loses the ability to specify http proxy authentication ([#{auth}]), but it can work for now.  I'm unsure of the best method to permanently fix it.  Maybe rules scope expansion to schemes/paths, maybe something else.

**Comment by qwj** [comment]
I have added filter rule to both host_name and port in pproxy v2.2.5
To fix this issue, add port 80 filter to the first "-r httponly+ssl://" and no filter to the second "-r http+ssl://".

`$pproxy -vv -l http://127.0.0.1:3136 -r httponly+ssl://proxy:9002?{80} -r http+ssl://proxy:9002`
`Serving on 127.0.0.1:3136 by http `
`http 127.0.0.1:53488 -> httponly+ssl proxy:9002 -> microsoft.com:80`
`http 127.0.0.1:53490 -> http+ssl proxy:9002 -> www.microsoft.com:443`

**Comment by daspri** [comment]
It does work for microsoft (http redirected to https), but it still does not work on http redirects with that squid proxy. 
```
curl -x http://127.0.0.1:3136 -A "" "http://google.com" -v -L
```
or 
```
curl -x http://127.0.0.1:3136 -A "" "http://httpbin.org/absolute-redirect/2" -v -L
curl -x http://127.0.0.1:3136 -A "" "http://httpbin.org/relative-redirect/2" -v -L
```
The previous "tunnel" does work.

**Comment by qwj** [comment]
I have fixed a bug in httponly connection reuse case.
Can you try again with pproxy v2.2.6?

**Comment by daspri** [comment]
It is working, thank you.
