### ISSUE TITLE
backward proxy behind another proxy

### ISSUE THREAD

**Issue by mosajjal** [qwj/python-proxy#66]
Hi,

in the command:

`pproxy -l http+in://client_ip:8081`

is there a way to connect to `client_ip` via another HTTP proxy? I've tested it with `proxychains` and it works, but I couldn't find the right syntax for `pproxy`

Cheers,

**Comment by qwj** [comment]
There is no such syntax in one line command. But you can run two proxies like this:

```
pproxy -l tunnel{client_ip:client_port}:///tmp/socket -r SOME_HTTP_PROXY -vv
pproxy -l http+in:///tmp/socket -vv
```

**Comment by mosajjal** [comment]
Thanks a lot :) Probably not a bad idea to add it to README

**Comment by pouyamiralayi** [comment]
@qwj is there any approach for this on windows where there is the lack of unix sockets?

**Comment by qwj** [comment]
@pouyamiralayi you can use localhost:port instead of unix sockets on Windows
