### ISSUE TITLE
http and httponly

### ISSUE THREAD

**Issue by serl** [qwj/python-proxy#68]
Hello,
my current upstream proxy works well if using CONNECT with HTTPS and GET with HTTP. I guess this is how web browser do, as it works well for everyone else in the company.

With pproxy, anyway, I have some issues:
- `pproxy -r http://proxy:port`
  - HTTP: 'unauthorized' error page from the upstream proxy
  - HTTPS: it works as it should
- `pproxy -r httponly://proxy:port`
  - HTTP: it works, but some http headers are probably being changed by pproxy
  - HTTPS: times out

So, I managed to find a workaround: `pproxy -r http://proxy:port?{443} -r httponly://proxy:port?{80}`. Which mostly works, but fails when the websites use nonstandard ports...

Any advice for a better solution?

Thanks!

**Comment by qwj** [comment]
It depends on how the remote proxy accepts CONNECT request with other ports.
pproxy uses first_available policy when you specify multiple remote -r, so you can assign first remote proxy with port=80 and don't assign port to the second remote proxy.

```pproxy -r http://proxy:port?{443} -r httponly://proxy:port```

**Comment by serl** [comment]
Thanks for the advice!
Doing some poking with netcat, I actually verified what you said: only port 443 is allowed on CONNECT, your solution works. :)
