### ISSUE TITLE
http+ssl not working

### ISSUE THREAD

**Issue by sameer-j** [qwj/python-proxy#7]
Unable to get http+ssl working. 
I started the server with `pproxy -i http+ssl://:8080 --ssl server.crt,server.key -v`, 
then configured by windows LAN setting to use secured
![image](https://user-images.githubusercontent.com/2439128/44715828-5a545680-aad6-11e8-906c-966f1d17cfee.png)

then when i try to access the page, i get "This page isn't working" on the browser. And i see no requests on the proxy  server.
I created the ssl files using the commands you provided.

**Comment by qwj** [comment]
If you want to setup http proxy in windows LAN setting, just use http instead of http+ssl

**Comment by sameer-j** [comment]
The aim is to use http+ssl proxy

**Comment by qwj** [comment]
http+ssl should not be supported in windows LAN setting

**Comment by sameer-j** [comment]
Why not? 
And not just windows, I not able to make it work for a webapp also.

**Comment by qwj** [comment]
windows IE don't have http+ssl proxy support
