### ISSUE TITLE
Redir Errors

### ISSUE THREAD

**Issue by oed-mertenss** [qwj/python-proxy#70]
Hello,

i want to use pproxy as transparent proxy on my local machine behind a corporate firewall.
I got a proxy that supports http. I sometimes switch from the corporate environment to my local home wifi where i dont need a proxy.

**My Setup:**
- Ubuntu 18.04
- iptables chain splitted by http/https (because http can't handle http requests it just handles https requests)
`sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to-ports 3126`
`sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to-ports 3127`

PProxy started as follows:
`pproxy -l redir://:3126 -a 3 -r httponly://proxyip:8100 -vv`
`pproxy -l redir://:3127 -a 3 -r http://proxyip:8100 -vv`

**The Problem:**
When I'm in my home wifi (no proxy) then he iterates over local ports show following errors million times:
```
...  (repeated for every port!)
2020-02-04 15:21:36 redir ::1:41882 -> ::1:3126
2020-02-04 15:21:36 redir ::1:52950 -> ::1:3126
2020-02-04 15:21:36 redir ::1:52990 -> ::1:3126
2020-02-04 15:21:36 redir ::1:53046 -> ::1:3126
2020-02-04 15:21:36 redir ::1:53092 -> ::1:3126
2020-02-04 15:21:36 redir ::1:53138 -> ::1:3126
... (repeated for every port!)
socket.accept() out of system resource
socket: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 3127)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 168, in _accept_connection
  File "/usr/lib/python3.6/socket.py", line 205, in accept
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('0.0.0.0', 3127)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 168, in _accept_connection
  File "/usr/lib/python3.6/socket.py", line 205, in accept
OSError: [Errno 24] Too many open files
```

Im not sure what the problem is. Normally he should check that the proxy is not available and he should switch to direct connections.

When i use 
`pproxy -l http://:3126 -a 3 -r httponly://proxyip -vv`
everything works like expected without errors.

Seems for me that the "redir" feature has a problem. It would be awesome if you can fix that :)

**Comment by qwj** [comment]
The iptables intercept a connection to port:80, redirect to pproxy. The pproxy tries to make a connection to remoteproxy:80, and it was intercepted by iptables rule, sent to pproxy again. Repeat and repeat. It is a dead loop.
You should change the iptables rule, make it not to intercept outgoing connection for the remoteproxy. An alternative way is to use different remoteproxy port other than 80.

**Comment by oed-mertenss** [comment]
Ah sorry i cutted to much the remote proxy port is 8100. So the explained loop should not happen.

**Comment by qwj** [comment]
The error shown above is a dead loop. Traffic to port other than 80 is redirected to pproxy. You can check whether the iptables work as expected.

**Comment by oed-mertenss** [comment]
That cant be the problem either because when im in the corporate network everything works like expected just when i switch to an open wifi and the proxy is not reachable anymore it is not working anymore. So something might be not working with the alive command.

**Comment by oed-mertenss** [comment]
Is there something that i can do to fix that problem? I can't do python :(

**Comment by qwj** [comment]
This error was caused by infinite loop redirected by iptables. pproxy can't fix anything.

**Comment by oed-mertenss** [comment]
are my iptables then incorrect?
