### ISSUE TITLE
tunneling to local port 

### ISSUE THREAD

**Issue by Geks0n34** [qwj/python-proxy#73]
Hi devs!
i`ve try build following scheme but it seems hard to do by provided features as my goal not a "proxy" and actualy reverse tunnel, is any pproxy scheme do needed tunnel reverse?
Thx!
![image](https://user-images.githubusercontent.com/36445933/77257516-9d0fed80-6c7d-11ea-8091-b02720201f5e.png)

**Comment by qwj** [comment]
If you want a udp tunnel, you can try to run like "pproxy -ul tunnel{8.8.8.8:53}://:53"
