### ISSUE TITLE
get error on ubuntu 16 for run ss server

### ISSUE THREAD

**Issue by karimi12** [qwj/python-proxy#74]
i run this command:  
pproxy -ul ss://chacha20:abc@0.0.0.0:8080

i get this error:
usage: pproxy [-h] [-i LISTEN] [-r RSERVER] [-b BLOCK] [-a ALIVE] [-v]
              [--ssl SSLFILE] [--pac PAC] [--get GETS] [--version]
pproxy: error: unrecognized arguments: -ul ss://chacha20:abc@185.203.1180.180:8080

**Comment by karimi12** [comment]
i use this command:
   pproxy -r  ss://chacha20:abc@0.0.0.0:8080
but i get this message:
Serving on :8080 by http,socks

**Comment by qwj** [comment]
You are running an old version of python-proxy

**Comment by karimi12** [comment]
pproxy --version
pproxy 1.2.2
