### ISSUE TITLE
i can't install last version

### ISSUE THREAD

**Issue by karimi12** [qwj/python-proxy#75]
i user this command for install :
 pip3 install pproxy

but:
pip install pproxy
Collecting pproxy
  Using cached pproxy-1.2.2-py3-none-any.whl (33 kB)
Installing collected packages: pproxy
Successfully installed pproxy-1.2.2

how can i fix it?

**Comment by karimi12** [comment]
this command not work 

pip install -Iv pproxy==1.9.5

**Comment by qwj** [comment]
You should have at least Python 3.5
python-proxy stop supporting Python 3.4 from 1.2.2

**Comment by karimi12** [comment]
python3 -V
Python 3.5.2

**Comment by qwj** [comment]
You should have at least Python 3.6
python-proxy stop supporting Python 3.5 from 1.2.2
