### ISSUE TITLE
Backward http proxy drops some requests

### ISSUE THREAD

**Issue by notstupidname** [qwj/python-proxy#77]
Hi!

I have an issue trying to set up backward proxy behind NAT.

Here is what I'm trying to do:
`client (browser) --> public_ip_server --> server_behind_nat --> internet`

So I followed example in README:

on public_ip_server
`pproxy -l http://:8088 -r http+in://8089`

on server_behind_nat:
`pproxy -l http+in://public_ip_server:8089`

It kinda works, but when I'm opening any page in the browser, it can't load ~10% of page resourses  randomly. Like, sometimes it's google fonts or jquery or any other external js, sometimes it's some images on the page. If I refresh the page several times, it's usually gets fully loaded, but not always.

Here is some logs from `public_ip_server`:

```
Serving on :8088 by http
Serving on :8089 backward by http
http 83.97.20.171:53834 -> http :8089 -> None:80
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d75857fa8>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 83.97.20.171
http 107.172.5.181:50884 -> http :8089 -> None:80
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d78b9edc8>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 107.172.5.181
http 109.252.131.20:9190 -> http :8089 -> mozilla.cloudflare-dns.com:443
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d75857fa8>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 109.252.131.20
http 206.81.1.172:46502 -> http :8089 -> None:80
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d78b9edc8>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 206.81.1.172
http 23.254.201.182:44326 -> http :8089 -> None:80
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d75857fa8>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 23.254.201.182
http 83.97.20.171:40470 -> http :8089 -> None:80
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d78b9edc8>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 83.97.20.171
http 109.252.131.20:16420 -> http :8089 -> yandex.ru:443
http 109.252.131.20:16427 -> http :8089 -> firefox.settings.services.mozilla.com:443
http 109.252.131.20:16433 -> http :8089 -> avatars.mds.yandex.net:443
http 109.252.131.20:16436 -> http :8089 -> yastatic.net:443
Task <Task pending coro=<Queue.get() running at /usr/local/lib/python3.6/asyncio/queues.py:167> cb=[_release_waiter(<Future pendi...d755e1558>()]>)() at /usr/local/lib/python3.6/asyncio/tasks.py:310]> got Future <Future pending> attached to a different loop from 109.252.131.20
http 109.252.131.20:16437 -> http :8089 -> yastatic.net:443
```

And here is logs from `server_behind_nat`:
XX.XX.XX.XX - public_ip_server
```
Serving on XX.XX.XX.XX:8089 by http 
2020-04-11 10:58:36 http XX.XX.XX.XX:8089 -> yandex.ru:443
2020-04-11 10:58:37 http XX.XX.XX.XX:8089 -> firefox.settings.services.mozilla.com:443
2020-04-11 10:58:38 http XX.XX.XX.XX:8089 -> avatars.mds.yandex.net:443
2020-04-11 10:58:39 http XX.XX.XX.XX:8089 -> yastatic.net:443
2020-04-11 10:58:39 http XX.XX.XX.XX:8089 -> yastatic.net:443
2020-04-11 10:58:39 http XX.XX.XX.XX:8089 -> yabs.yandex.ru:443
2020-04-11 10:59:05 http XX.XX.XX.XX:8089 -> None:80
2020-04-11 10:59:05 [Errno -3] Temporary failure in name resolution from XX.XX.XX.XX
2020-04-11 10:59:14 http XX.XX.XX.XX:8089 -> mozilla.cloudflare-dns.com:443
2020-04-11 11:00:07 http XX.XX.XX.XX:8089 -> None:80
2020-04-11 11:00:07 [Errno -3] Temporary failure in name resolution from XX.XX.XX.XX
```

Also, I have ssh on `public_ip_server`, so I tried to create reverse tunnel from `server_behind_nat` like so:
`ssh -R 8088:localhost:8089 user@public_ip_server`
and then:
`pproxy -l http://:8089`

It works without any problems, but I want to achieve this without ssh server, keys and all that stuff.

**Comment by qwj** [comment]
Hi,

Did you enable uvloop? If yes, you can disable uvloop and try again.
You can also try change http+in:// to ss+in:// to see if there is difference.

**Comment by notstupidname** [comment]
I don't know what uvloop is and how to enable it, so I guess I didn't.

I tried ss+in, socks5+in and socks4+in, it makes no difference.

Maybe there is a way to create a reverse tunnel like with ssh? I didn't completely understood WebSocket and Tunnel examples in README. Is it possible to use them in backwards mode?

**Comment by qwj** [comment]
I guess the backward proxy works fine. But the http proxy listened in http://:8088 doesn't handle all requests properly. Can you try other protocol or listened in other ports?

**Comment by notstupidname** [comment]
I can't use any other protocol for a proxy because my client is actually a webdriver and it can only use plain http proxy. I tried different ports, no effect.

If I use it like this:
`client --> public_ip_server --> internet`
with `pproxy -l http://:8088` on a `public_ip_server` it works completely fine.

Also, with ssh tunnel between `public_ip_server` and `server_behind_nat` and http proxy on `server_behind_nat` it also works fine.

**Comment by qwj** [comment]
I don't know what's wrong. But from the logs, I can see the connections with backward proxy is good. The http://:8088 is having protocol compatibility issue. Some request's hostname "None" is totally wrong. Maybe the webdriver is not fully compatible with pproxy's http server protocol.

**Comment by notstupidname** [comment]
This logs are actually from normal Firefox that I used for testing. 

Yeah, I see that something is wrong with first proxy:

`http 83.97.20.171:45004 -> http :8089 -> None:80
Unknown remote protocol from 83.97.20.171`

But I only get those messages if I use two proxies. If I only use first proxy on `public_ip_server`, I don't get those errors. Same webpage, same browser, same everything..

Is there a way to create backwards tunnel with tunnel or ws?

**Comment by qwj** [comment]
You can try tunnel+in:// with these:

public_ip_server:
```pproxy -l tunnel://:8088 -r tunnel+in://:8089```

server_behind_nat:
```pproxy -l http+in://public_ip_server:8089 -vv```

public_ip_server doesn't handle the protocol and forward all connections to server_behind_nat. server_behind_nat can specify any protocol like http/ss/socks5

**Comment by notstupidname** [comment]
Yeah, it's working that way! Kinda slow and I still get some errors with `-> None:80` on `server_behind_nat`, but pages got loaded eventually!

Also, it only works with http+in://, with ss/socks5 I got
`Unsupported protocol b'C' from XX.XX.XX.XX`

Thank you for your help!
