### ISSUE TITLE
Python-proxy on Android or Windows

### ISSUE THREAD

**Issue by ingnelson** [qwj/python-proxy#78]
Hello guys .
Is there a way to use python-proxy on Android or Windows as client ? 
The server on a VPS and create the tunnel ?
Maybe the app send the request and connect to shadowsocks app via local Host ? 

I would like to use it on Android or Windows , please .

**Comment by qwj** [comment]
You can install Python on Windows.
python-proxy is compatible with Windows system.
It seems there is no way to use standard Python on Android system.

**Comment by ingnelson** [comment]
@qwj one more question sir. 
If someone create a app and the sockdroid as a template or base ? 
https://github.com/ycmmonkey/socksdroid

I am not a expert , I just want to be clear .

**Comment by qwj** [comment]
there are many socks clients on android with similar features

**Comment by ingnelson** [comment]
@qwj there is app called Qphyton for Android too.
https://play.google.com/store/apps/details?id=org.qpython.qpy3

Is it not possible to use python-proxy on Android ?

**Comment by qwj** [comment]
If it is compatible with standard Python 3.6, python-proxy will be possible to run.

**Comment by ingnelson** [comment]
@qwj can you create a script to run it on Qphyton for Android , please , I am not a programmer . It will not take you much time . You are a master .

**Comment by ingnelson** [comment]
@qwj I am willing to pay

**Comment by ingnelson** [comment]
someone create a app to send a encode URL request and inside that app is the ip and port then he use shadowsocks app to create the tunnel via local Host.
I have one question : is it possible he is using shadowproxy ?? The URL is encode .
Request :

GET #0=a179912768a2445fd9900d471690f81c&1=0&2=s&ss=1589252103950&ope=1# HTTP/1.1
ٌُُُُُُّّّّْْْْْْْْْْْْْْْْْْ
Look the screenshot :
![806527796_30481](https://user-images.githubusercontent.com/6626845/81733004-91a39c00-944e-11ea-85af-71d0116f7b59.jpg)
![Screenshot_2020-05-12-12-16-20-769_com github shadowsocks](https://user-images.githubusercontent.com/6626845/81733085-abdd7a00-944e-11ea-9d7b-a0dd36a12ed1.jpg)

Look the request :
![107736462_243730](https://user-images.githubusercontent.com/6626845/81733213-de877280-944e-11ea-97c8-8e2da7e00d4b.jpg)


Please I need your opinion and know if he is using your method .
