### ISSUE TITLE
pproxy Blacklist

### ISSUE THREAD

**Issue by oed-mertenss** [qwj/python-proxy#79]
Hi,

im stuck at the moment i have some local domains that should get a "direct" connection instead of tunneling through the proxy.

So far i tried to make that work via the "rules" option.
As far as i understand the code the ProxyURI.compile_rule does the work.

It just compiles regex patterns joined by "|". (like: `(:?rule)$`)

e.g. The example of your github readme.md:
`(:?.*google\.com)`

The opposite should work like i want:
`(:?^(?!.*(google\.com)).*$)$`

To test i wrote a small python test script:
```
import re

reg = re.compile("(:?^(?!.*(google\.com)).*$)$")

if(reg.match("www.google.com")):
    print ("google.com via proxy")
else:
    print("google.com via direct")

if(reg.match("heise.de")):
    print ("heise.de via proxy")
else:
    print("heise.de via direct")
```
The test python script works like expected!

Why pproxy dont work? I don't get it can you please help me?

**Comment by qwj** [comment]
Hi,

A more convenient way is to add direct.regex like this:

```pproxy -r direct:///?direct.regex -r http://remote_ip:remote_port/
```

The matching rule is first_available. If direct.regex matches, traffic go directly by scheme "direct:///".

**Comment by oed-mertenss** [comment]
Aw im stupid thanks! That solved it!

**Comment by oed-mertenss** [comment]
Argh that is not working in "redir" Mode. Do you may have another idea?

**Comment by oed-mertenss** [comment]
Just tried now to open 2 servers
1. redir:3128 -> local http proxy:3129
2. local http proxy:3129 -> remote http proxy

Looks like there is already a dns lookup on the first server so the second cant do directs anymore.

**Comment by qwj** [comment]
With "-l redir://" using "-r direct://" will cause infinite loop unless you have two network interfaces.
You can view iptables documents to see how to redirect only necessary traffic.

**Comment by oed-mertenss** [comment]
I tried this already:
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 13 --dport 80 -j REDIRECT --to-port 3128
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner 13 --dport 443 -j REDIRECT --to-port 3128

i let the user where pproxy is running to direct connect to 80/443 is there no way where i can negate the rules?

**Comment by qwj** [comment]
Sorry. I am not familiar with iptables rules.

**Comment by oed-mertenss** [comment]
Don't worry can you may tell me why the regex negotiation is not working in the rules part?
Or is it possible to add a feature not just for whitelisting also for blacklisting?

**Comment by qwj** [comment]
The match rules not only match host but also match port number string.

```
def schedule(rserver, salgorithm, host_name, port):
    filter_cond = lambda o: o.alive and (not o.match or o.match(host_name) or o.match(str(port)))
```

It provides feature that you can put whitelisted ports in rules.
So it is impossible to get the opposite regex rules with only hostname.
The port number filter would pass.

**Comment by qwj** [comment]
You can use direct:/// scheme to make blacklisted filters:

```
pproxy -r http://server1?whitelist.regex -r http://server2
pproxy -r http://server2?blacklist.regex -r http://server1
```
Two above commands are all the same.

There is a hidden direct:/// after the last "-r" server, so the following two are the same.
```
pproxy -r http://server1?whitelist.regex
pproxy -r direct:///?blacklist.regex -r http://server1
```

**Comment by oed-mertenss** [comment]
I dont get you i think.

I can reproduce all that i know it is working with an http proxy. My setup is as follows:
linux system 80,443 -> iptables redirect to 3128 -> pproxy in redir mode:3128 -> I want to choose here where to go if direct or via proxy -> remote proxy:8080

because then i dont have to handle complex ip/network based iptable rules i just direct everything to pproxy in redir mode it handles for me the rest.

using direct is working fine in http mode but not in redir mode.
thats why i try to invert the rules regex in the hope that then i can get it to work in redir mode.
