### ISSUE TITLE
asynchronous proxy

### ISSUE THREAD

**Issue by Thibault-Daccord** [qwj/python-proxy#8]
Hey, 

Do you have a way to run pproxy asynchronous  (Thread) ? 
something like: 
`pproxy.main(asynchronous = True)`

If yes can we kill this ?
something like: 
`pproxy.stop()`

Thx

**Comment by qwj** [comment]
pproxy is implemented by asyncio,
you can stop it by loop.stop() using asyncio API.
before modifying the code, you should be familiar with python3 asyncio API.
