### ISSUE TITLE
Wrong handling IPv6 connection

### ISSUE THREAD

**Issue by CrazyLionHeart** [qwj/python-proxy#82]
On server-side got error: `invalid literal for int() with base 10: 'xxxx:xxxx:xxx:face:xxxx:x:xxx:443' from xx.xx.xx.xxx`

On client-side: `Unknown remote protocol from ::1`

Version: pproxy==2.3.4

**Comment by qwj** [comment]
Can you print the parameters and protocols in details?

**Comment by CrazyLionHeart** [comment]
Server: `pproxy -v -l http://:8010/#login:pass`
Client: `pproxy -vv -r http://ipv4:8010\#login:pass --sys`

Client OS - Mac OS X 10.15.5
Client have both address - ipv4/ipv6
Server have both address - ipv4/ipv6

**Comment by qwj** [comment]
Can you help test whether pproxy==2.3.5 still has this issue?
