### ISSUE TITLE
Question about how it can work

### ISSUE THREAD

**Issue by panpansh** [qwj/python-proxy#84]
hello, I have a question concerning the implementation to know if it is planned so that it works like that ? : 
I would like to know if it is possible that this works like a reverse tcp shell in a "simple" way ?
In this case there would be 3 actors, right ? :
- a (base) client that want the socks5.
- a central server that acts as a connecting proxy.
- and the "reverse tcp proxy socks" which goes to the destination desired by the base client ?

Best regards.

**Comment by qwj** [comment]
Yes, it is possible.
Please read the README.md to get details.
