### ISSUE TITLE
Per host/url proxy rules supporting.

### ISSUE THREAD

**Issue by hongyi-zhao** [qwj/python-proxy#88]
Hi,

Does pporxy support the proxy rule per host/url/site?

Best regards,
HY

**Comment by qwj** [comment]
Yes, it supports.
You can specify remote_proxy#rule_file to give a regex rule.

**Comment by hongyi-zhao** [comment]
> Yes, it supports.
> You can specify remote_proxy#rule_file to give a regex rule.

Still, I'm not so clear on this feature, could you please direct me to some more specific documents?

**Comment by qwj** [comment]
You can see the README.md for the document of regex rule.

**Comment by hongyi-zhao** [comment]
Thanks a lot, I noticed the [examples](https://github.com/qwj/python-proxy#examples). But I still want to know where is the location for the rules file. Can I specify the rules file relative/absolute path in the command, say, similar to the following:

`$ pproxy -r http://aa.bb.cc.dd:8080?(relative|absolute)/path/to/rules -vv`

**Comment by qwj** [comment]
relative/absolute path is both supported
