### ISSUE TITLE
IPv6 address issue

### ISSUE THREAD

**Issue by h12345jack** [qwj/python-proxy#89]
https://github.com/qwj/python-proxy/blob/0aa4e4c6c9afbbf20cb97e9174a426513b738f11/pproxy/server.py#L477

Hello, it looks like this line can't handle the following cmd line:

```pproxy -r ss://aes-128-gcm:password@xx:xx:xxx:xxx:xxx:port --sys -vv```

It should be revised as 
```
loc.rpartition(':') # add r
```

Thank you

**Comment by qwj** [comment]
Thank you. It will be fixed in v.2.3.7
