### ISSUE TITLE
use case

### ISSUE THREAD

**Issue by thestick613** [qwj/python-proxy#9]
I have the following use case:
1.1.1.1:1000 - a tcp service
2.2.2.2:2000 - a http proxy with authentication
On 3.3.3.3, i need to open a service which listens to port 3000, and tunnels all the requests to 1.1.1.1:1000 via the 2.2.2.2:2000 proxy.

So when i telnet 3.3.3.3:3000, i should be able to talk to 1.1.1.1:1000.

socat works just fine, but it creates a new pid for every connection and it is kind of slow and unreliable.
Can python-proxy be used for this case?

**Comment by qwj** [comment]
It may work to start pproxy on machine 3.3.3.3 with following parameters:
$ proxy -i tunnel{1.1.1.1:1000}://:3000 -r
http://2.2.2.2:2000#username:password -vv

**Comment by thestick613** [comment]
I think you meant -l instead of -i, but it works. Thank you.

**Comment by qwj** [comment]
Oh, a typo. With pleasure :)
