### ISSUE TITLE
Request: Tagged Releases

### ISSUE THREAD

**Issue by drewrisinger** [qwj/python-proxy#91]
Looking at the pypi repo for this project, the version numbers are clear. However, it's not clear when looking at this Git repo which commit corresponds to which version release. Would you be able to tag the commits corresponding to the pypi releases going forward? Something akin to how numpy does it: https://github.com/numpy/numpy/tags

The main reason I am asking is that I repackage this library for use in some software distributions, and I prefer to run your tests whenever possible. However, those tests are only included in the GitHub source, and not the tar.gz sdist on pypi, necessitating fetching from the GitHub repo.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository

**Comment by yan12125** [comment]
Hi @qwj is there a plan to implement this?

FWIW, with the help of tools like `setuptools_scm`, the version for `setup.py` will be automatically generated from the current git tag. That should minimize efforts on keeping git tags and PyPI versions in sync.

**Comment by jayvdb** [comment]
I am wanting to package this for openSUSE, and I also need tagged releases, and even better would be for the PyPI sdist to contain the test modules.

**Comment by qwj** [comment]
@yan12125 setuptools_scm was added. Thanks for the commit and advices.

**Comment by yan12125** [comment]
Thanks, the latest PyPI sdist works fine!
