### ISSUE TITLE
-r 指定上级代理服务器 not working

### ISSUE THREAD

**Issue by Woodrowww** [qwj/python-proxy#94]
centos 7

服务器
pproxy -l http+socks4+socks5://:8033/ -vv -r socks5://10.21.214.222:1080

10.21.214.222:1080是可以正常使用的socks5服务器

测试
curl --socks5-hostname 127.0.0.1:8033 "www.baidu.com"
服务器输出日志：
socks5 127.0.0.1:45752 -> socks5 10.21.214.222:1080 -> www.baidu.com:80
但是curl一直在等待，没有输出，不是网速问题，因为直接curl "www.baidu.com"是正常的，"www.baidu.com"换成内网服务器用ip访问也一样的问题。

如果不使用上级代理，直接 `pproxy -l http+socks4+socks5://:8033/ -vv`，是正常的

**Comment by qwj** [comment]
你好，
可以用
pproxy -r socks5://10.21.214.222:1080 --test http://baidu.com
测试远程socks5服务器的可用性

**Comment by Woodrowww** [comment]
> 你好，
> 可以用
> pproxy -r socks5://10.21.214.222:1080 --test http://baidu.com
> 测试远程socks5服务器的可用性

做了一些测试，这几个测试里面只有用pproxy创建的socks5代理服务器，才能被pproxy使用。

      pproxy -l socks5://:1234
      Serving on :1234 by socks5 

10.17.172.74是我本地ip

     docker run --rm mosajjal/pproxy:latest -r socks5://10.17.172.74:1234 --test http://baidu.com
     正常输出

1235是我用goproxy创建的socks5代理，用curl测试正常，用pproxy测试有报错

      curl    --socks5-hostname  10.17.172.74:1235 ww.baidu.com
      正常输出

      docker run --rm mosajjal/pproxy:latest -r socks5://10.17.172.74:1235 --test http://baidu.com
      报错

============ 10.17.172.74:1235 ============
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pproxy/server.py", line 502, in test_url
    reader, writer = await roption.prepare_connection(reader, writer, host_name, port)
  File "/usr/local/lib/python3.6/site-packages/pproxy/server.py", line 395, in prepare_ciphers_and_headers
    await self.rproto.connect(reader_remote=reader_remote, writer_remote=writer_remote, rauth=self.auth, host_name=whost, port=wport, writer_cipher_r=writer_cipher_r, myhost=self.host_name, sock=writer_remote.get_extra_info('socket'))
  File "/usr/local/lib/python3.6/site-packages/pproxy/proto.py", line 208, in connect
    await reader_remote.read_until(b'\x00\x05\x00\x00')
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 572, in readuntil
    raise IncompleteReadError(chunk, None)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of None expected bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pproxy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pproxy/server.py", line 546, in main
    asyncio.get_event_loop().run_until_complete(test_url(args.test, args.rserver))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/pproxy/server.py", line 505, in test_url
    raise Exception('Unknown remote protocol')
Exception: Unknown remote protocol


另外 ssr client创建的socks5代理，也是用curl测试可用，用pproxy测试就无限等待，没有报错

**Comment by qwj** [comment]
可以试一下最新版v2.3.9
解决了这个问题

**Comment by Woodrowww** [comment]
> 可以试一下最新版v2.3.9
> 解决了这个问题

解决了。神速啊，太优秀了。

docker hub里面的版本还是不能用，好像pproxy的版本和docker包的版本是不一样的。
docker run --rm mosajjal/pproxy:2.3.9-uv --version
pproxy 2.2.0
