### ISSUE TITLE
rules文件中表示取反的规则不能生效

### ISSUE THREAD

**Issue by Woodrowww** [qwj/python-proxy#95]
需求：
对10.*.*.*的ip使用direct，对其他任意hostname使用 -r 指定的服务器。

pproxy -l socks5://:1234/ -vv -r socks5://remote:1080?rules 

rules文件：
(?!10).*

rules文件的规则是非10开头的host使用remote，10开头的host不使用remote。

测试：
curl --socks5-hostname 127.0.0.1:1234 "10.17.172.74:8081"
服务器日志输出
socks5 127.0.0.1:49586 -> socks5 remote:1080 -> 10.17.172.74:8081
不能达到预想的效果。

workaround：
在本地创建一个local-proxy。
pproxy -l socks5://:1234/ -vv -r socks5://local-proxy:1080?direct -r socks5://remote:1080?rules 

direct文件：
10.*

rules 文件：
.*

这样可以满足上述需求，但是需要专门创建一个local-proxy。 
如果允许 -r direct?rules 这样的写法，会方便一点，或者是不是我没搞懂正确的用法？

**Comment by qwj** [comment]
可以用
pproxy -r direct://?rules -r socks5://remote
获得类似效果

**Comment by Woodrowww** [comment]
解决了
