### ISSUE TITLE
How to convert a socks5 proxy to https proxy?

### ISSUE THREAD

**Issue by hongyi-zhao** [qwj/python-proxy#96]
Hi,

I still can't figure out how I can convert a socks5 proxy to HTTPS proxy using python-proxy. Any hints will be highly appreciated.

Regards,
HY

**Comment by Jonney** [comment]
pproxy -l http+ssl://127.0.0.1:8080 -r socks5://x.x.x.x:port#user:pass

**Comment by hongyi-zhao** [comment]
Tries the above form but failed as shown below:

```
$ pproxy -l http+ssl://127.0.0.1:18080 -r socks5://127.0.0.1:18888
You must specify --ssl to listen in ssl mode
```

**Comment by qwj** [comment]
The errors say what to do: "You must specify --ssl to listen in ssl mode"

**Comment by hongyi-zhao** [comment]
Thanks a lot for your notes. But I'm still not so clear on how to prepare/generate the ssl certfile/keyfile as described by the help of pproxy:  
```
$ pproxy -h | egrep -- '^[ ]*--ssl'
  --ssl SSLFILE     certfile[,keyfile] if server listen in ssl mode
```
Any hints will be highly appreciated.

Regards,
HY
